### ISSUE TITLE
感谢分享，新版有些问题

### ISSUE THREAD

**Issue by wysl** [liwanggui/bssh#1]
我之前使用上一个版本可以正常在winodws上使用；这个新版本我在server2008和win8上试了下好像有些问题，运行命令后只提示了SSH和sftp登陆成功，并没有做任何操作，python版本2.7.11；linux 还没有试

**Comment by liwanggui** [comment]
麻烦看下主机日志文件是否有信息， 我在windows server 2008上测试没有出现你说的问题， 我会在Windows 其他版本系统继续测试，在进行修复的。
